[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
lazy_static = "1.4.0"

axum = "0.4.8"
tokio = { version = "1.17.0", features = ["full"] }

tracing = "0.1.32"
tracing-subscriber = "0.3.9"
